### ISSUE TITLE
Cantor's teepee is not totally separated

### ISSUE THREAD

**Issue by prabau** [pi-base/data#122]
https://topology.jdabbs.com/spaces/S000126/properties/P000048

As mentioned on that page, this is shown in Steen & Seebach item 3 for space 129, and I can understand the argument in the book.

But I cannot make sense of the alternative argument in pi-base.  Assuming U_p and U_q are disjoint (not mentioned, but I assume that's the case).  The boundary of U_p must intersect L(c).  So far so good.  But why does that imply the existence of t in C such that $\delta U_p \cap L(t) \cap X$ is nonempty?  (for example it could be that a point in L(c) intersect boundary of U_p is an isolated point of the boundary of U_p that does not even belong to X, and there are no nearby points in the triple intersection above.)

Furthermore, the argument in the book makes essential use of the fact that Cantor's leaky tent (i.e. with the apex added back) is connected, which is a highly nontrivial result.  But the alternative argument above makes no use of that fact. It seems it would be too simple to work.

Maybe I am missing something simple.  Do you guys think the alternative argument works?

**Comment by prabau** [comment]
Hi @gb-solis @tomaszrz1 If you have the chance, could you take a look at this issue and see what you think?  Trying to get feedback on this from recent fellow pi-base contributors.

**Comment by StevenClontz** [comment]
I haven't thought much about this one, but I'll note that many proofs in the pi-Base were contributed by undergraduates in a course developed around using the pi-Base a few years back (2015ish maybe? it was before I was officially involved in the project directly). So while we've since made an effort to audit the property and theorem data, any proofs from that period haven't been reviewed closely. I'd accept a PR that removes a questionable proof, since we have the Counterexamples citation to rely on.

Also maybe this question is worth posing on Math.Stackexchange?

**Comment by prabau** [comment]
Thanks Steven.  I'll do a PR for this in a few days. (Don't really think it's worth asking on stackexchange, as I am pretty sure the additional proof is not correct.)
And thanks @gb-solis and @tomaszrz1 anyway.

**Comment by ccaruvana** [comment]
Sorry for the delay on looking this over @prabau . Thank you for the detailed work on this space!

**Comment by prabau** [comment]
> 
> 
> Sorry for the delay on looking this over @prabau . Thank you for the detailed work on this space!

No problem. Thanks!
