### ISSUE TITLE
Citing the pi-Base

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#256]
Ryan added a citation file in #253 which brought up the question: how should pi-Base be cited?

I put @jamesdabbs and myself as that's how Buzzard cited us in https://arxiv.org/pdf/2112.11598.pdf (the only known citation I'm aware of in "literature").

On the other hand, LMFDB suggests "The LMFDB Collective". https://www.lmfdb.org/citation and OEIS uses "OEIS Foundation Inc" https://oeis.org/wiki/Works_Citing_OEIS#Referencing_the_OEIS

We call ourselves "a community database of topological counterexamples". So maybe "The pi-Base Community" is best?

**Comment by prabau** [comment]
(from PR #253)
> As a whole this works, but this is a blunt instrument. I'd love to have individual contributions be citable, e.g. if you visit https://topology.pi-base.org/theorems/T000332 you'd get a citation that makes it clear that @ccaruvana contributed it. (Then again, maybe one of the answers from https://math.stackexchange.com/questions/103774/every-manifold-is-locally-compact is more appropriate?)

Personally I think if someone really needs to find out who contributed to what in a specific file, the best tool for that is github/git itself and its history feature.  Especially as multiple people may have touched a file, and multiple versions may have made changes on top of each other.  Otherwise, for general usage I'd say something like the "pi-base community" is a pretty good solution.

**Comment by ccaruvana** [comment]
I also agree with "the pi-base community".

**Comment by StevenClontz** [comment]
See #260
