### ISSUE TITLE
T107 improvement

### ISSUE THREAD

**Issue by prabau** [pi-base/data#325]
https://topology.pi-base.org/theorems/T000107
As written some things in the justification seem kind of sloppy.  I am not even sure anything can be concluded from the last sentence ("an infinite set with no limit point").

We could add a ref to the Answer to https://math.stackexchange.com/questions/95668 for example and point to that for the details.  Or anything else that makes sense.

**Comment by prabau** [comment]
@lyengulalp Assigned to you if you want to practice with this.
Btw, the editor I did not remember the name of in the meeting is vscode (= Visual Studio Code).  The github web based editor is based on that: see https://docs.github.com/en/codespaces/the-githubdev-web-based-editor.  It's also available standalone on Mac, Windows, Linux as an alternative.

**Comment by prabau** [comment]
I realize I did not correctly express what I meant.  First of all, from the fact that $\{V_\beta\}$ is infinite one cannot conclude that the $x_\beta$ have no limit point.  For example https://topology.pi-base.org/spaces/S000005: a partition topology with each block in the partition consisting of more than one point; every nonempty subset (infinite or not) in that case has a limit point.  Furthermore, the fact that every infinite set has an cluster/accumulation point is not enough to conclude the space is countably compact.  In the example above it's not countably compact.  From wikipedia, what matters is $\omega$-accumulation point and not just accumulation point (which would correspond to the weaker concept of https://en.wikipedia.org/wiki/Limit_point_compact.)

Basically this approach with limit points seems to make things harder than necessary, compared for example with the last paragraph of https://math.stackexchange.com/a/95687.

Also, earlier in the pi-base justification, the "without loss of generality bit" is not trivial. That's the general fact that a point finite covering of a set $X$ has an irreducible subcover, proved in the mathse post above.  Also, "$\{V_\beta\}$ is a minimal such subcovering" is confusing: it's not a subcovering of anything mentioned earlier in the justification (although what can guess what they meant, take an irreducible subcover of ..., blah blah blah)

In any case, I thought this should be fixed and expanded, or easier, removed altogether and replaced with a reference to some mathse post for example.  What do you think?

**Comment by lyengulalp** [comment]
Ah, I see. I think like the original author of T000107, non-T1 spaces are a blind spot for me. 

Here is a shortening of the proof found at  https://math.stackexchange.com/a/95687
Let X be metacompact and countably compact. Suppose \mathcal{U} is an open cover and let \mathcal{V} be a point-finite open refinement. Consider the set A of subcollections of \mathcal{V} that cover X ordered by inclusion. Using the point-finiteness of \mathcal{V}, one may see that the intersection of a chain in A is also a cover of X. By Zorn's Lemma, A has a \subseteq-maximal element, \mathcal{V}', which therefore is an irreducible cover of X (no proper subcollection of \mathcal{V}' covers X). Since X is countably compact, \mathcal{V}' must actually be finite. Otherwise, if \mathcal{V}'' is a countably infinite subcollection of \mathcal{V}', let V = \bigcup \mathcal{V}'' and note that the countable cover \mathcal{V}'' \cup {V} has no finite subcover, contradicting countably compact. 
Even with the details that are skipped, is that too big for a pi-base proof? If so, then sure, we can just point to the SE post.


I also found a reference (not free) with the proof. Theorem 107 is one case of Corollary 2.4 in the following paper: Wicke, H. H., and J. M. Worrell. “Point-Countability and Compactness.” Proceedings of the American Mathematical Society, vol. 55, no. 2, 1976, pp. 427–31. JSTOR, https://doi.org/10.2307/2041739.

Main Theorem: Suppose X is a countably compact topological space and \mathcal{U} is the union of a countable collection {\mathcal{V}_n, n \in \omega} of collections of open subsets of X such that each x \in X is in at least one element but not in more than countably many elements of some \mathcal{V}_n. Then some finite subcollection of \mathcal{U} covers X.

Corollary 2.4: If a countably compact space has any of the properties listed in the diagram (one of which is metacompact), then it is compact.



For those who are more familiar with the pi-base standards, what is the ideal entry for this theorem? Proof sketch + one or both references, or simply the SE reference (since it seems to be complete)?

**Comment by prabau** [comment]
(I put $$ around some of the math to make it easier to read and replaced inclusion with reverse inclusion.)  At the end of the proof, shouldn't it be $V=\bigcup(\mathcal V'\setminus\mathcal V'')$?  Anyway, the proof is not correct.

Nice paper you found  (the doi is pointing to the free version, not jstor).  They also mention that the particular result of T107 it was proved in https://eudml.org/doc/114685 (MR 0038642) by Arens and Dugundji (1950).  That's a small paper just for that theorem.  I find it interesting historically that in 1950 they were still using the classical terminology "bicompact" for compact and "compact" or "Frechet-compact" for countably compact.

What's the best way to present the theorem in pi-base then?  We always need references.  On top of that, if a proof is really small (not much more than one or two lines), we have often optionally written it down explicitly.  Otherwise, we just refer to the references for details (or give a hint of the argument and refer to the refs?).  Your proof is not super small, but maybe ok to have it.  In any case, I think it would be worthwhile to add to the references both the mathse post and either the Proc. AMS article or the Arens-Dugundji article.  @StevenClontz, @ccaruvana: have I gotten this right?

**Comment by prabau** [comment]
@lyengulalp sorry typo above.  I meant to say the proof is now correct.

**Comment by lyengulalp** [comment]
Oh nice, I didn't realize I could use $$. 

The Arens and Dugundji paper uses T1 (it uses the equivalence of countably compact and every infinite set has a limit point). I don't object to including it as an additional reference though.

**Comment by prabau** [comment]
No, [limit point compact + metacompact ==> compact] is not true: https://topology.pi-base.org/spaces?q=metacompact%2Blimit%20point%2B~compact.  So Arens-Dugundji must be assuming T1 then (they seem to be using this implicitly in the equivalence between the characterization of limit point compact and countably compact).  So we should probably not refer to that paper.

How about adding your proof then, together with a ref to the mathse answer and also mention Corollary 2.4 of the other paper without further details?

**Comment by prabau** [comment]
FYI, what we have been doing when referring specifically to an answer to a mathse post when the question itself is not exactly about the topic is point to the answer itself (click on "Share" below the answer to get a url) and add something like what was done for example for T194 and many other examples.

**Comment by ccaruvana** [comment]
I think including the argument sketch with two references (one to a peer reviewed article and one to se) is good. So I agree with @prabau including the proof, a ref to mathse, and the corollary from the Wicke/Worrell paper.

**Comment by lyengulalp** [comment]
Will work on it tonight...slowly so I don't screw something up.
