### ISSUE TITLE
normal + countably metacompact => countably paracompact

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#345]
See [corollary 2 on Dan Ma's blog](https://dantopology.wordpress.com/tag/metacompact-space/).
I think this should be added as a new theorem to pi-base.

**Comment by prabau** [comment]
Yes, that would be very good to add.  As you probably realized by now, there are many theorems that are currently not in pi-base and that would be good to have.  There are also traits (= property files for specific spaces) that could be deduced from existing theorems that could be cleaned up.  And also some redundancies among existing theorems.  And add new example spaces.  These are just some of the things we could do to make pi-base more usable and valuable as a repository of information.

Would you be interested in contributing a PR (pull request) that we could review and incorporate?  If so, please let us know and we'll give a few pointers about the process.

**Comment by Moniker1998** [comment]
Yes, I could do that, though I never contributed anything on github.
By the way, I commented on this https://github.com/pi-base/data/pull/343 pull request with contributions to which spaces on pi-base are realcompact, properties of long line that needs fixing etc. I'm not sure if that was a proper place to do that in.

**Comment by prabau** [comment]
Your comments on #343 are fine, so we don't lose them.  In general, we prefer to do multiple bite-sized PRs, as they are easier to review and incorporate, instead of a massive catch-all contribution.  So we'll get to it, but it may take a while, in many chunks.

In any case, very glad to have you on board.  There is no rush on this, even if it takes a week or two.  You should first familiarize yourself with github and the use of git.  There are various tutorials around (on youtube also, I think) and help pages.  I forgot exactly, but when you first join github, I think it presents you with a tutorial to create your first repo ("hello-world"?).  You can go through that, create a dummy repo and play with it.   If you can't find anything, let us know and we can try to track things down.  Do you have any prior experience with git itself?

Once you are comfortable with how that works, we can give you more specific instructions about pi-base. 

@StevenClontz Anything else you want to add?

**Comment by Moniker1998** [comment]
I don't have any experience with git, no. I imagine it boils down to editing/creating a text file by using a PR which then gets approved.

**Comment by prabau** [comment]
Well, it's more than that.  Git is the underlying source code control system used to track changes.  It's important to have a conceptual understanding of it, at least at a high level.  I recommend watching some youtube videos about it for example.  Again, no need to getting too deep into it, but need to understand the notion of branch, commits, etc.  At least the basic workflow. Lots of videos around.
Also look at https://docs.github.com/en, create dummy hello-world repo, play with it, etc.

**Comment by StevenClontz** [comment]
I have a video at https://www.youtube.com/watch?v=TKxN8xxz0VY going through making edits to the pi-Base. However, I think the big shortcoming with it is that it doesn't go through the steps of forking, necessary for external contributors.
