### ISSUE TITLE
Alternate definition of locally compact

### ISSUE THREAD

**Issue by jamesdabbs** [pi-base/data#42]
This suggestion came in through email

> I was looking at the definition of “locally compact” property at $\pi$-base. In my version of Willard’s “General Topology”:
>
> 18.1 Definition. A space $X$ is locally compact iff each point in $X$ has a nhood base consisting of compact sets.
>
> And the current $\pi$-base definition is
>
> A space $X$ is locally compact if each point of $X$ has a compact neighbourhood.
These definitions match for Hausdorff spaces, but not even for locally Hausdorff ones! See
>
> https://math.stackexchange.com/a/337657/58818
>
> The $\pi$-base definition coincides with Munkres’ (Sec 29), Kelley (p. 146), and Counterexamples’, though... But Willard’s definition seems overall more in vogue nowadays at least for Operator Algebras.

It's worth considering if this is a point where we want to make another break with counterexamples sim. the `T_n`s, or just want to add another property (and maybe links between them).

**Comment by StevenClontz** [comment]
We should definitely list both properties, just as there are two notions of monotone paracompactness depending on author (although I believe we list neither currently). I wonder if "locally" is more commonly used to mean "each point has a relevant neighborhood" or "each point has a relative neighborhood base"; often this is equivalent (e.g. locally metrizable).

**Comment by StevenClontz** [comment]
This also illustrates why I think mathoverflow and math.SE should be supported citations for the pi-base. This space should be added to the pi-base as the counter-example to "locally compact (Munkres) => locally compact (Willard)"!

**Comment by luizgcordeiro** [comment]
Hi. I was the one who made the suggestion by e-mail. Here are another 2 cents.

I would say that "Every point has a nhood basis with such property" is what we end up using in practice for local properties, whereas the weaker version is used when the property pass to subspaces; e.g. Hausdorff and metrizability; Local (path-)connectedness and contrability are also quite useful, and we need the stronger version.

Local normability is funny, since normability passes only to closed subspaces;  so we can only guarantee that a **regular** space s.t. every point has a normal nhood is locally normal (in the strong sense).

Moreover, even the regular property may be seen as "local property" in the stronger sense: A space is regular iff every point has a nhood basis of closed sets. (and the weaker version is trivial).

Thanks for considering my comment. I really appreciate you work at the $\pi$-base.

**Comment by StevenClontz** [comment]
@luizgcordeiro That was were my mind was headed as well. I think the convention "locally P" means "has a nbhd base of sets satisfying P" is reasonable, and clarify otherwise. So https://topology.jdabbs.com/properties/P000023 could be renamed "Locally compact by a single neighborhood" and we should add a new "Locally compact", along with some relevant theorems.

**Comment by StevenClontz** [comment]
I've written this up (along with some other conventions) here: https://github.com/pi-base/contributing/blob/master/CONVENTIONS.md

**Comment by StevenClontz** [comment]
Looking around, I see that "weakly locally compact" is often used for the single-neighborhood case, vs. "locally compact" for a neighborhood base. So in an upcoming PR I'll adjust the conventions to use "locally P" and "weakly locally P" consistently (while updating https://topology.jdabbs.com/properties/P000023 ).

**Comment by prabau** [comment]
Steen & Seebach also use the terminology "strongly locally compact" = Every point has a closed compact nbhd.  
= properties (2),(2'),(2'') in https://en.wikipedia.org/wiki/Locally_compact_space. = Property P000024 in pi-base.

I understand the desire for consistency in pi-base's terminology.  pi-base currently does not have a term for property (3), which would be useful to introduce.   But if we switch the meaning of "locally compact" and introduce "weakly locally compact" (= (1) in wikipedia page) as proposed, we would have the situation that "locally compact" (= (3) in wikipedia page) would imply "strongly locally compact" and not the reverse, which can be confusing.

What is more common in the literature?

**Comment by StevenClontz** [comment]
Oh thanks for catching that @prabau; I'd completely blanked that P000024 is already in the pi-base. And this made me realize that https://topology.jdabbs.com/theorems/T000006 is incorrect - it should imply (weakly) locally compact. https://topology.jdabbs.com/spaces/S000029 should be a counterexample.

From what I've seen, "locally compact" is defined as convenient for the subject at hand, and often the spaces considered are Hausdorff so there's no ambiguity anyway.

So perhaps we do this: "strongly locally P" means there's a basis of P neighborhoods, "weakly locally P" means there's a single P neighborhood, and "locally P" is used exactly when those notions are equivalent.

**Comment by StevenClontz** [comment]
I only have the 1st page access at the moment but https://www.jstor.org/stable/24340250 seems relevant to this discussion.

**Comment by StevenClontz** [comment]
And now I see that Steen/Seebach's strongly locally compact is not what I'm suggesting either - I was thinking about the definition in https://www.jstor.org/stable/24340250  (-:

After re-reading the March 2019 discussion above though, I think it's just another break we should make from Steen/Seebach for consistency. It just means we also need to rename P24 (and note in its definition the original terminology).

**Comment by prabau** [comment]
With the current terminology for "strongly locally compact" (= property (2) in wikipedia = every point has a *closed* compact nbhd), https://topology.jdabbs.com/theorems/T000006 is correct (since the whole space is a closed compact nbhd of any point).

"strongly locally compact" in https://www.jstor.org/stable/24340250 that you mentioned is a different notion, I agree.  Although that reference is not really classical.  (Engelking assumes locally compact spaces are Hausdorff so avoids all the issues)

**Comment by StevenClontz** [comment]
I lean toward consistency over classical, particularly when (as you say) it's all negligible assuming Hausdorff. But if you'd prefer different adverbs for "weakly/strongly locally P" since "strongly locally compact" is not isolated in the literature in referring to wikipedia's (2) I'm open to ideas.

**Comment by prabau** [comment]
Well, the weakest condition is wikipedia (1), which we could rename as "weakly locally compact".  Wikipedia (3) is what is suggested to rename to just "locally compact" (which agrees with Willard), so that seems ok.  

But then, as you suggest, it would be good to rename P000024 to something else than "strongly locally compact".
From https://en.wikipedia.org/wiki/Relatively_compact_subspace, a "relatively compact subset" is a subset with compact closure. 
Wikipedia (2'): Every point has a relatively compact nbhd.  Wikipedia (2''): Every point has a local base of relatively compact nbhds.  So we could call that property (2) "locally relatively compact" maybe?
It matches https://projecteuclid.org/download/pdf_1/euclid.pjm/1102720477 p. 134.  It's only one reference though.

Wikipedia already uses the terminology "strongly locally compact" with Steen/Seebach's meaning in https://en.wikipedia.org/wiki/Particular_point_topology for example.  So we would deviate from that.  Maybe ok.

**Comment by prabau** [comment]
One more observation: "relatively compact" is a hereditary property.  Every subset of a relatively compact set is relatively compact.  So if there is one such nbhd, there is a local base of such nbhd.  So no need to distinguish between "locally relatively compact" and "weakly locally relatively compact".  (That's the equivalence between (2') and (2'') in wikipedia.)

To confuse things even further, nlab mentions still a fourth notion of local compactness:
"local compactness via compact closures inside neighbourhoods" (def. 2.2 in https://ncatlab.org/nlab/show/locally+compact+topological+space) which is not listed in wikipedia.
I don't think we need to introduce that right now in pi-base.

**Comment by prabau** [comment]
Trying to summarize all the various names so far and how they fit with the wikipedia article (and nlab),
assuming your proposed convention "weakly locally P" = each point has a nhbd with property P, and "strongly locally P" = each point has a local base of nbhds with property P (and "locally P" when weak and strong are the same).  I think I would prefer a simpler convention, but going with this for the below:

[the numbers below refer to the various definitions in https://en.wikipedia.org/wiki/Locally_compact_space
(1) = "weakly locally compact"
(2) = "locally relatively compact" (same for weak and strong)
(3) = "strongly locally compact"

Wikipedia does not have the corresponding "strongly locally closed-and-compact" (in your proposed terminology).  That would correspond to def. 2.2 in https://ncatlab.org/nlab/show/locally+compact+topological+space.  Maybe it should be added to wikipedia?
The corresponding "weakly locally closed-and-compact" is identical to wikipedia (2) = "locally relatively compact", since if there is a nbhd whose closure is compact, there is one which is closed and compact.

Terminologywise, wouldn't it be simpler to revert to the current  convention that "locally P" means there is a nbhd base satisfying P for each member of the base?  And just introduce "weakly locally P" for the weak case in case it is needed, i.e., in case they are different?

Then:
(1) = "weakly locally compact"
(2) = "locally relatively compact"
(3) = "locally compact"
(new) = "locally closed-and-compact"  (Def 2.2 in nlab)  (maybe introduce this?)

**Comment by prabau** [comment]
I read the Pi Mu Epsilon article you mentioned and am starting to like your proposed terminology "locally closed-and-compact".  There are two dimensions that can vary: weak vs. strong, and compact vs. closed and compact.  That gives 4 possibilities.

Personally I think it would be simpler to revert to the current convention that "locally P" means there is a nbhd base satisfying P for each member of the base.  And just introduce "weakly locally P" for the weak case in case it is needed, i.e., in case they are different.  What do you think?

So the 4 possibilities would be:
- "weakly locally compact" = wikipedia (1)
- "locally compact" = wikipedia (3)
- "weakly locally closed-and-compact" = wikipedia (2) (which would be the same as "locally relatively compact")
- "locally closed-and-compact" (missing from wikipedia, but same as def 2.2 in  https://ncatlab.org/nlab/show/locally+compact+topological+space)

How would that look?

**Comment by StevenClontz** [comment]
Dropping "strongly" avoids the name collision with Steen/Seebach, so I'm happy with that.

I won't add locally closed-and-compact in #63 but a new PR that includes a counterexample distinguishing it from locally relatively compact would be nice.
