### ISSUE TITLE
Careful handling of "Has a Dispersion Point" and "Biconnected" in spaces of cardinality less than four

### ISSUE THREAD

**Issue by hew-wolff** [pi-base/data#470]
"Has a Dispersion Point" (https://topology.pi-base.org/properties/P000045) says that a dispersion point is one whose removal makes a connected space totally disconnected. But this appears to mean that any connected space of size 1 or 2 has a dispersion point, since any space of size 0 or 1 is totally disconnected (https://topology.pi-base.org/properties/P000047). This contradicts, for example, "Indiscrete Topology on a Two-Point Set" (https://topology.pi-base.org/spaces/S000004/properties).

Maybe we should follow Wikipedia (https://en.wikipedia.org/wiki/Dispersion_point) and say that "Has a Dispersion Point" also requires the space to have at least 3 points.

**Comment by StevenClontz** [comment]
Good call. #471 will say 

>  [Totally Disconnected](https://topology.pi-base.org/properties/P000047) and [Has distinct points](https://topology.pi-base.org/properties/P000125)

mirroring https://topology.pi-base.org/theorems/T000052

**Comment by prabau** [comment]
I am not sure I necessarily agree with this change of the definition of P45.  A few observations:

(1) We all agree that the interesting cases are spaces with a good number of points.  The spaces with very small (<= 3) cardinality are fringe cases.  Whether we want them covered or not by some definitions does not really matter.  We either specify explicitly that some small spaces (even though they match the definition) will not have the property.  Or we don't specify that.  It's a matter of either keeping the definition simple, or of making some theorems simpler.

(2) Wikipedia is not an authoritative source of information, unless they are backed up by reliable sources.  In this case, https://en.wikipedia.org/wiki/Dispersion_point has no inline citation to back up their choice of requiring a space with a dispersion point to have at least 3 points.  And furthermore, the article by Abry, Dijkstra, van Mill in the References section does **not** have that requirement.

So we should investigate this more and see what other sources are saying.

(3) for the case of S4 (indiscrete space with two points), the reason pi-base marks it as having no dispersion point is due to T92 (dispersion point ==> biconnected) in combination with the assertion Biconnected = false.

But that last assertion is in fact incorrect.  Given the definition of Biconnected that we use, for a connected space to be biconnected, it must not be the union of two disjoint connected subsets, each with size at least two.  So to witness that a connected space is not biconnected, you need at least four points.  Any connected space with at most three points will be vacuously biconnected.

So fixing the assertion about biconnectedness will solve that immediate problem.

(4) It may be true though that the definition for P45 is not optimal.  I looked at some of the early sources that introduced the notion of biconnectedness (Knaster & Kuratowski 1921) and dispersion point, and they are sometimes sloppy in the statements of their theorems.  They seem to totally ignore the cases of very small cardinality, where their results are not strictly true.

As an instructive example worth taking a look at, the short paper: Kline (1922) "A theorem concerning connected point sets" (http://matwbn.icm.edu.pl/ksiazki/fm/fm3/fm3124.pdf) proves that a connected space can have at most one dispersion point (equivalent to our definition).  But that's patently false for both the indiscrete space with two points and for the Sierpinski space.

For now I am inclined not to change the P45 definition, but we need to give this more thought.  Any comments?

**Comment by StevenClontz** [comment]
At a glance, I think the suggested change would allow http://matwbn.icm.edu.pl/ksiazki/fm/fm3/fm3124.pdf to be correct: the author assumes that the removal of a dispersion point creates a non-connected space, which is true for a totally disconnected space with multiple points.

I think this assumption is more natural for P45, but not enough to spend a lot of time deliberating it for the handful of topologies that have less than four points. (Hmm, does [S162](https://topology.pi-base.org/spaces/S000162) have a dispersion point?)

**Comment by prabau** [comment]
I guess we could go that way.  To address my point (3) above, we should also fix the biconnected trait for S4.

@hew-wolff What's your take on this?

**Comment by hew-wolff** [comment]
I'm not sure what the best fix is--I'm just learning about these terms and I don't have any relevant texts. But as a learner, I would prefer that we have definitions that work in all cases, even very small spaces. Otherwise it gets confusing.

Can we find some fairly recent sources and work out a fix that's compatible with them?

**Comment by prabau** [comment]
I am not sure I understand what "definitions that work in all cases" or a fix "compatible with very small spaces" would even mean.

It's similar to the fact that the empty set is compact (because it vacuously satisfies the definition of compact), or a singleton is connected (because it vacuously satisfies the definition of connected).  The corresponding (modern) definitions are whatever they are, with no special provision for degenerate cases, and very small spaces happen to satisfy the definition or not depending on the property.

The alternative would have been to specify for example that connected spaces also require at least two points.  In fact, that's exactly what pioneers like Knaster & Kuratowski (1921) and others did in their original works.  Later on, I guess it was realized that to get simply phrased theorems like the continuous image of a connected space is connected, it was easier to allow singletons to also be connected instead of adding some extra condition in the theorem itself.  For "dispersion point", one can similarly either put an extra size condition in the definition or not. Both notions will coincide if the space has enough points.  And the cases of very small spaces are degenerate cases that are of little interest.
(but one could look at a few recent sources like you suggest)

**Comment by StevenClontz** [comment]
The continuous image of connected is connected, and every constant map is continuous, so we probably want singletons to be connected.

**Comment by prabau** [comment]
For what it's worth, I looked at old and more recent papers and could not find an instance where the definition is stated as requiring at least three points.  But it does not matter really.  Enough time spent on this, I'll approve whatever you guys want to do.

One thing though: https://topology.pi-base.org/spaces/S000010/properties/P000045 should be changed at the same time as the definition change.

**Comment by hew-wolff** [comment]
I would just like to avoid statements that are false. I feel they might bite me unexpectedly.

If this issue is too small to raise, or if it should come with a more detailed proposal, let me know and I'll try to do better next time.

**Comment by StevenClontz** [comment]
@hew-wolff thanks for your contribution. I what this and the conversation at https://math.stackexchange.com/questions/4812062/ has revealed is the need for properites to designate spaces with 3 or 4 points, after which we can introduce theorems to enforce whatever decision we want for dispersion point.

I'm going to edit #471 to introduce the property `Cardinality \geq 3` and `Cardinality \geq 4`, and appropriate theorems to wire those with dispersion points and biconnectedness. I'm actually unsure now whether to keep the has multiple points requirement for dispersion point, but maybe with having these cardinalities expressed as properties and enforced by theorems the right solution will pop out...

**Comment by StevenClontz** [comment]
As expected I eventually hit a contradiction with the assertion at https://topology.pi-base.org/spaces/S000010/properties/P000045 (thanks @prabau for pointing this out so I wasn't caught off-guard), see https://github.com/pi-base/data/actions/runs/6990837011?pr=471 

@jamesdabbs originally made pi-Base to digitize Steen/Seebach's *Counterexamples*. I think we correctly go against *Counterexamples* for some conventions, e.g. $T_3$ should imply $T_2$. But in this case I don't think one convention is better than the other, and *Counterexamples* clearly defines a dispersion point to create a totally disconnected space, and clearly believes discrete implies totally disconnected. So I'm updating #471 to revert to our current definition of a dispersion point to keep in line with *Counterexamples*.

**Comment by StevenClontz** [comment]
Here's a fun puzzle:

```
build: spaces/S000001/README.md#L1
properties=P000175,P000129,P000052,P000078 contradict 
theorems=T000092,T000095,T000429,T000088,T000316,T000280,T000249,T000218,T000187,T000042,T000078
```

One of these theorems must assume spaces have at least three points... (-:

**Comment by StevenClontz** [comment]
![image](https://github.com/pi-base/data/assets/1559632/47d6e117-7139-44ad-a69c-fff8bb4393cf)

**Comment by StevenClontz** [comment]
Posted at https://math.stackexchange.com/questions/4814244/where-is-pi-base-assuming-the-existence-of-at-least-three-points though I'm still working on it.

**Comment by StevenClontz** [comment]
Got it, we do require connected for a dispersion point, so my new T429 requires connected as an assumption.

**Comment by StevenClontz** [comment]
Okay #471 gets us a few steps in the right direction, but I got carried away with adding a bunch of three-point spaces and need to let someone approve the work so far before doing more.
