### ISSUE TITLE
Contribution workflow

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#5]
Here's a proposed workflow for contributions. Once it's decided on, we should have this in CONTRIBUTING.md.

1. New contributions are made via pull request.
2. James's custom CI tool (is this on GitHub?) automatically makes the following guarantees:
    - no duplicated stubs
    - no contradictions
    - citations in every file
    - Others?
3. If the PR passes the above checks, an Editor (right now just Steven) verifies that the contribution is supported by its citations
4. Once approved by the editor (through what mechanism?), the CI tool makes the following enhancements:
    - builds appropriate UIDs
    - others?
5. CI tool merges new contribution to master and delivers updated database to jamesdabbs/pi-base-viewer

**Comment by jamesdabbs** [comment]
The validator is on Github @ `pi-base/validator` (incidentally, I was thinking about keeping any related tools under the `pi-base` org down the road).

There are two families of checks to run: internal consistency ones, and diff checks (e.g. did a theorem get deleted? Did a trait change value? Are we okay with that?) For now (and maybe for always), it's probably just a matter of commenting with a warning rather than literally disallowing those sorts of destructive updates.

We _could_ wire up the "approval" to literally be clicking the merge button, but I sort of imagine that you'll want it to be something you can kick off manually from whatever tool you end up using to facilitate reviews. The validator is a Yesod app, and so could easily have an admin area for these sorts of things.

**Comment by StevenClontz** [comment]
Moving all these projects to pi-base org makes sense to me. Feel free to add me as a collaborator; I'm dreaming of a future where I can contribute code as well as math. (Right now I'm working on a math ed Rails app that's hogging my time though: https://github.com/stevenclontz/sbg-rails )

I imagine that when I get a reviewable PR (it passes the first check for trivial issues), I'll want to edit it in the same tool I use to make my own contributions, then send it back off to a tool in the cloud that handles the final merging into the repo and updating the viewer. I've never worked with CI tools or Yesod myself, so I'm only vaguely aware of the standard way of doing things, if there is such a thing.

**Comment by StevenClontz** [comment]
Closing as stale
