### ISSUE TITLE
Clean up metacompact traits made redundant by T442

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#551]
Observed at https://math.stackexchange.com/questions/4856141/sigma-compact-and-hausdorff-implies-paracompact

Shows https://topology.pi-base.org/spaces/?q=%24%5Csigma%24-compact%2B%24T_2%24%2B%7EMetacompact cannot have results, adds traits for e.g. https://topology.pi-base.org/spaces/S000053/

(Traits should be cleaned up)

**Comment by GeoffreySangston** [comment]
@StevenClontz Do you have a suggestion for how to do this? Should I just click the Person icon at https://topology.pi-base.org/properties/P000031/spaces, and go down the list to see which of the spaces still derive Metacompact upon adding all of their properties + ~Metacompact to the Explore bar?

@danflapjax Do you have a tool which could automate that process by the way? I.e., if space X has traits A, B, C, D, then the tool just checks each of the Explore strings '~A + B + C + D', 'A + ~B + C + D', 'A + B + ~C + D', 'A + B + C + ~D' to see if any ever returns a contradiction / is impossible derivation. If 'A + ~B + C + D' returns a contradiction, then B gets displayed to the user of the tool as a redundant trait. I haven't actually investigated the web part of pi-base's infrastructure at all, but is that easy the way things are set up? (I'm also happy to learn about the web infrastructure part eventually.)

**Comment by StevenClontz** [comment]
We definitely need tooling for this. @danflapjax has a bunch of cool things that I would love to either port to pi-Base or organize into more organized tools we can link from https://topology.pi-base.org/dev

**Comment by danflapjax** [comment]
> Do you have a tool which could automate that process by the way?

I did actually make something to list out all of the traits that can be derived from the others in the database; you can check it out here: https://observablehq.com/d/4198053ce0c15799

A word of care, however: just because a set of traits are listed doesn't mean *all* of them can be removed, as two could imply each other. One could totally make something to output the minimal sets of traits to determine the rest, but this is not something I have done. I'll have more time to spend on implementing stuff for pi-base once my final exams are done next week though.

**Comment by GeoffreySangston** [comment]
Okay I'm going to use this tool right now to clean these up, as an experiment.

**Comment by StevenClontz** [comment]
@danflapjax you inspired me: there is now a warning displayed on trait pages when a trait can be deduced from the other asserted traits: https://topology.pi-base.org/spaces/S000025/properties/P000065
