### ISSUE TITLE
Restate contrapositive theorems

### ISSUE THREAD

**Issue by marswill** [pi-base/data#567]
In general, it seems we probably don't want to state theorems in the form 

$$(\text{Other Properties}) \wedge \neg A \implies \neg B,$$

 as these can be reformulated 

$$(\text{Other Properties}) \wedge B \implies A.$$

I counted a bunch of these and would ordinarily just do a PR myself to restate them, but I'm a bit preoccupied at the moment so I thought I'd record them here for me (or anyone else) to tackle later.

[T83](https://topology.pi-base.org/theorems/T000083)
[T89](https://topology.pi-base.org/theorems/T000089)
[T134](https://topology.pi-base.org/theorems/T000134)
[T262](https://topology.pi-base.org/theorems/T000262)
[T391](https://topology.pi-base.org/theorems/T000391)

**Comment by marswill** [comment]
Note that the descriptions in some of these might need to be rephrased slightly for the proofs to make sense.

**Comment by prabau** [comment]
It may not be completely clear cut.  Let me go through two of these cases as an example.

T83: three equivalent formulations:
- (1) loc arc connected + not discrete ==> not card < c (the current version)
- (2) loc arc connected + card < c ==> discrete
- (3) not discrete + card < c ==> not loc arc connected

For (1), discreteness is an auxiliary property compared with loc arc connected.  Saying (not discrete) is a kind of non triviality condition in this context.  And semantically, (not card < c) is just a way of saying (card >= c).  It appears as a negative just because of the way we chose to formulate the cardinality properties.  So really (1) is saying: except in a trivial context, if $X$ is locally arc connected, its cardinality will be at least c, which sounds very natural to me.
Is (2) really better in this case?

T134: three equivalent formulations:
- (1) Baire + meager ==> empty
- (2) Baire + not empty ==> not meager (the current version)
- (3) meager + not empty ==> not Baire

I guess (1) is more symmetric and implies (2) and (3), which could be considered at the same cognitive level.  (2) and (3) are really the two formulations used by folks when using T134.  We could convert to (1) so as to give (2) and (3) equal weight in a way.

**Comment by marswill** [comment]
Hmm, you make a pretty compelling case actually.  In fact looking at all of these examples, I think your argument seems to carry the day.  While there's a symmetry argument in favor of changing the Baire one, I'm not sure that really is persuasive - in all of these cases (except the cardinality one) you have one trivial property  (indiscrete, discrete, or empty) that would end up as the conclusion, and that is probably not what we want.  And the Cardinality one is quite clear the way it's stated as well.

I'll be honest, I caught myself thinking similar things in the back of my mind shortly after I posted this.

I'm kind of inclined to just close this issue as one of my less well-thought out ideas :)
