### ISSUE TITLE
Use T###### for theorems.

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#6]
(original issue was much broader but now only asks to do this:)

Can we easily change I###### to T###### for theorems?

**Comment by jamesdabbs** [comment]
`I` is for implication so that `T` can be for trait. That's largely because I could think of a different word for theorem before one for trait. That said ... traits don't really even need an ID now, right? They're always specified by the (space, property) pair. So probably should reserve `T` for theorem.

**Comment by StevenClontz** [comment]
@jamesdabbs I assigned this to you, but it may be out of scope before next week. However, I think it'd be a good thing to knock out sooner than later if we're going to do this (for the sake of URLs). We'd probably want to forward /theorems/I##->/theorems/T## anyway.
