### ISSUE TITLE
The space $\omega_2$ or $\omega_12$: An example of LOTS+~compact+~first countable+countably compact

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#640]
(I am sorry to open up so many issues at a time, but I am afraid that I would forget if I didn't do that.)

Currently there is no space in pi-base that serves as an example of being LOTS+~compact+~first countable+countably compact. In fact, as stated in the last issue, any ordinal greater than $\omega_1$ with uncountable cofinality will do, so we can take the space $\omega_2$ or $\omega_12$ for example. The latter is the smallest such example.

**Comment by Jianing-Song** [comment]
By the way, do you think it is worthy to add the property "well-orderable", also known as "ordinal"? There are currently 10 ordinals in the database (S1 = $2$, S2 = $\omega$, S20 = $\omega+1$, S33 = $\omega\cdot 2$, S34 = $\omega\cdot 2+1$, S35 = $\omega_1$, S36 = $\omega_1+1$, S162 = $1$, S163 = $0$ and S189 = $3$), and the one mentioned in this post will add one more. We can then have:

Countable + discrete => well-orderable
Well-orderable => LOTS + scattered + well-based (no more need to prove the latter two properties specially for S36)
Well-orderable + ~countable => ~discrete (this rules out the last space (discrete topology on $\mathbb{R}$) which satisfies LOTS + scattered + well-based.

**Comment by prabau** [comment]
Having a property saying the space is (homeomorphic to) an ordinal space, i.e., a well-ordered LOTS (that is a LOTS whose order is a well-order) seems a good idea to me.  Like you mention, it allows to unify various results and automatically deduce traits for various spaces.

I am not completely sure what the best name would be though.  Thinking out loud, what could "well-orderable" mean by itself?  Is it the topology that is somehow well-ordered? (no, it's not) Is it the underlying set itself that is well-orderable? (every set is well-orderable) We could use "well-ordered LOTS", but since we already have "LOTS", that could lead to confusion when various properties are side by side in text.  What about "ordinal space"?  The name is short and descriptive, and if we give a careful definition, it should be clear that we mean anything homeomorphic to an ordinal space.
What do you think?

@ccaruvana @StevenClontz and others: any opinions?

**Comment by Jianing-Song** [comment]
> Having a property saying the space is (homeomorphic to) an ordinal space, i.e., a well-ordered LOTS (that is a LOTS whose order is a well-order) seems a good idea to me. Like you mention, it allows to unify various results and automatically deduce traits for various spaces.
> 
> I am not completely sure what the best name would be though. Thinking out loud, what could "well-orderable" mean by itself? Is it the topology that is somehow well-ordered? (no, it's not) Is it the underlying set itself that is well-orderable? (every set is well-orderable) We could use "well-ordered LOTS", but since we already have "LOTS", that could lead to confusion when various properties are side by side in text. What about "ordinal space"? The name is short and descriptive, and if we give a careful definition, it should be clear that we mean anything homeomorphic to an ordinal space. What do you think?
> 
> (We should also check what's used in the literature.)
> 
> @ccaruvana @StevenClontz and others: any opinions?

"Ordinal space" sounds great to me :)

**Comment by Jianing-Song** [comment]
Perhaps some of the properties for $\omega_1$ or $\omega_1+1$ can be stated more generally...
S20, S34, S36/P16: More generally, an ordinal space is compact if and only if it is empty or an successor ordinal.
S35/P19: More generally, an ordinal space is countably compact if and only if its cofinality is different from $\omega$.
S36/P81: More generally, an ordinal space $\ge\omega+1$ is not countably tight.
S36/P103: More generally, an ordinal space $\ge\omega+1$ is not strongly KC as $[0,\omega)$ is not closed.
