### ISSUE TITLE
The theorem T131

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#660]
I think that it is important to emphasize that the subspace topology of a connected GO-space coincides with its order topology, as has been done in the proof of T125 (the subspace topology of a compact GO-space coincides with its order topology).

Could we write something like "The subspace topology and the topology induced by the order on a {P36} (connected) subset of {P133} (LOTS) coincide. See Lemma 6.1 ..."?

Thank you in advance.

**Comment by prabau** [comment]
Sure, we could add something.  Note however that there is maybe a little confusion in the above.

T125 (GO-space + compact ==> LOTS) can be explained in several ways, depending on what we choose for the definition of GO-space.  The proof of T125 that is in pi-base makes no mention of any subspace topology.  You keep talking about the "subspace topology of a compact GO-space".  There is no such thing. (I can guess what you are trying to say, but it should be said correctly ...)

The proof of T125 uses the characterization of GO-spaces in terms of an ordered set $(X,<)$ together with a topology admitting a base consisting of order-convex sets (and such that the topology contains the order topology $\sigma$ induced by the order $<$).  (I used $\sigma$ instead of $\lambda$ from the paper.) There is no enclosing LOTS space anywhere, and no subspace of anything in the argument.  But the conclusion is that $\tau = \sigma$, that is, the topology on $X$ was in fact the same as teh order topology induced by the order $<$.

One could phrase things similarly for T131, without giving any details of the argument, but with precise statements at least, plus the reference to the paper.

Alternatively, one could phrase things with the alternate characterization in terms of subspaces of LOTS.  But that's a different thing.

With this said, can you propose again what you have in mind?

**Comment by Jianing-Song** [comment]
> Sure, we could add something. Note however that there is maybe a little confusion in the above.
> 
> T125 (GO-space + compact ==> LOTS) can be explained in several ways, depending on what we choose for the definition of GO-space. The proof of T125 that is in pi-base makes no mention of any subspace topology. You keep talking about the "subspace topology of a compact GO-space". There is no such thing. (I can guess what you are trying to say, but it should be said correctly ...)
> 
> The proof of T125 uses the characterization of GO-spaces in terms of an ordered set (X,<) together with a topology admitting a base consisting of order-convex sets (and such that the topology contains the order topology σ induced by the order <). (I used σ instead of λ from the paper.) There is no enclosing LOTS space anywhere, and no subspace of anything in the argument. But the conclusion is that τ=σ, that is, the topology on X was in fact the same as teh order topology induced by the order <.
> 
> One could phrase things similarly for T131, without giving any details of the argument, but with precise statements at least, plus the reference to the paper.
> 
> Alternatively, one could phrase things with the alternate characterization in terms of subspaces of LOTS. But that's a different thing.
> 
> With this said, can you propose again what you have in mind?


Thanks for the clarification.

Can just making it simple do? T125 goes: "Let $\tau$ be the topology on $X$ and let $<$ be the order on $X$ in the definition of GO-space, with corresponding order topology $\tau$". So I propose for T131: "The given topology on $X$ and the order topology induced by the order in the definition of GO-space coincide", or "The given topology on $X$ is precisely the order topology induced by the order in the definition of GO-space".

**Comment by prabau** [comment]
> "The given topology on $X$ and the order topology induced by the order in the definition of GO-space coincide"

I like this one.  Feel free to add it.
