### ISSUE TITLE
Space Property Suggestion: The Hilbert Cube is homogeneous

### ISSUE THREAD

**Issue by konradvoelkel** [pi-base/data#760]
(not sure if this is a "theorem" in the same way as the properties=>properties theorems)

## Theorem Suggestion

The Hilbert Cube [S32](https://topology.pi-base.org/spaces/S000032)
is homogeneous [P86](https://topology.pi-base.org/properties/P000086).

## Proof/References

The result is nontrivial and most proofs don't generalize well to properties=>properties theorems. Also, any way to prove a more general statement for infinite-dimensional compact convex subsets of \ell^2 are useless, as these are all homeomorphic to the Hilbert Cube anyway.

There is a nice discussion on [MSE](https://math.stackexchange.com/questions/2194/why-is-the-hilbert-cube-homogeneous) and in particular a link to the elementary proof [The Homogeneous Property of the Hilbert Cube](https://arxiv.org/pdf/1211.1363.pdf), by Denise M. Halverson, David G. Wright, 2012.

**Comment by danflapjax** [comment]
Great suggestion; I've been meaning to add this for a while since it would give an example of a nontrivial [homogeneous space with the fixed point property](https://topology.pi-base.org/spaces?q=Homogeneous+%2B+Fixed+point+property). (The real projective plane would be another nice one to add, but that's worthy of a separate issue.)

**Comment by danflapjax** [comment]
Resolved by #862
