### ISSUE TITLE
"almost discrete" property

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#807]
> That's called "almost discrete" in the literature, but there are variants depending on additional separation axioms or not.  We'll have to be a little careful when introducing this.  But definitely worth having.  It will simplify a lot of things.

_Originally posted by @prabau in https://github.com/pi-base/data/pull/804#discussion_r1803931583_

**Comment by prabau** [comment]
I'll make a list of the various variants in the literature and then we can discuss what we want to choose.

**Comment by prabau** [comment]
Here are some of the definitions of "almost discrete" from the literature.

(1) a Hausdorff space with precisely one non-isolated point.

Henriksen & Wilson, "Almost discrete SV-spaces", Topology Appl., 1992
(https://zbmath.org/0791.54049, https://www.sciencedirect.com/science/article/pii/016686419290123H)

(2) A space with precisely one non-isolated point.

A. Osipov, "On the product of almost discrete Grothendieck spaces", Topology Appl., 2024
(https://zbmath.org/1542.54005, https://arxiv.org/pdf/2312.10724)

(3) A space with at most one non-isolated point.

Hirata & Yajima, "Inequality and equality for the extent of products with a special factor", Top. Proc., 2022
(https://zbmath.org/1479.54020, http://topology.nipissingu.ca/tp/reprints/v59/tp59015p1.pdf for the first page, the rest of the article is not openly accessible)

(4) A space in which the set of isolated points is dense.

A. Estaji, "On almost discrete space", 2008
(https://zbmath.org/1212.54056, 
https://dml.cz/bitstream/handle/10338.dmlcz/108097/ArchMathRetro_044-2008-1_8.pdf)

F. Azarpanah, "Algebraic properties of some compact spaces", Real Anal. Exch., 2000
(https://projecteuclid.org/journals/real-analysis-exchange/volume-25/issue-1/Algebraic-Properties-of-Some-Compact-Spaces/rae/1231187606.full)

(5) some notion involving measure theory, not directly relevant

Feel free to comment.

**Comment by StevenClontz** [comment]
1) of course, we rarely assume separation axioms as part of a definition (they are easily added when needed) 

2/3) if we have discrete=>P properties that can be improved to almost discrete => P, using "at most" seems to make sense. 

4) would consider this too, but I could see this being another property in addition to 2/3

**Comment by prabau** [comment]
I would also favor (2) or (3).

It is true that with (3) one could generalize "discrete => P" to "almost discrete => P" in some cases.  I am not sure that is very important though.  How many such pi-base properties would that apply to?

If we went with (2), for some properties we would have both "discrete => P" and "almost discrete => P", which does not seem a big deal.

On the other hand, if we went with (3) and needed a space with exactly one non-isolated point, we would have to say "almost discrete + not discrete", which a little cumbersome.  Can you think of any theorems that would use specifically that?

The Top. Proceedings article from 2022 is the only one that seemed to use definition (3), as was mentioned in the zb review; but I did not look at the article itself.  Do you have access to that?

**Comment by StevenClontz** [comment]
I don't have access to the 2022 article from my current location, but looking at https://topology.pi-base.org/properties/P000052/theorems it's not clear to me that we'd get a lot of improvements if we went with (3), so I'm leaning (2) anyway.

**Comment by prabau** [comment]
I concur with (2).  @danflapjax, ok with you?

**Comment by danflapjax** [comment]
I think (3) ends up being a bit cleaner than (2) with regard to theorems. If we take (3), we have Door + Ultraconnected -> Almost discrete and Door + T2 -> Almost discrete (strengthening [T145](https://topology.pi-base.org/theorems/T000145)), yet for (2) these would need to be Door + Ultraconnected + Has multiple points -> Almost discrete and Door + T2 + ~Discrete -> Almost discrete, plus we would need the additional theorem Almost discrete -> Has multiple points. If there were any theorems whose antecendents would apply to almost discrete spaces but not discrete ones, that would support choosing (2), but I have not thought of any, nor does it seem anyone else has. As you brought up, needing to specify almost discrete and not discrete as traits is a strike against (3), but I don't think it's a big deal personally, since not discrete is very easy to show. I imagine there may be some theorems of the form Almost discrete + something -> Discrete as well toward that end.

Also, I realized that my construction at #813 works for any metrizable space with only finitely many points; are these also the ones to which (4) applies?

**Comment by StevenClontz** [comment]
Take the rationals, attach a countable disjoint sum of discrete sequences converging to each rational. This would be (4) but not(?) completely metrizable.

**Comment by prabau** [comment]
- [Door + Ultraconnected + Has multiple points -> Almost discrete] with def (2)
 is actually more informative than 
 [Door + Ultraconnected -> Almost discrete] with def (3).
It says that (assuming multiple points) $X$ has exactly one limit point.  Whereas the other version does not capture that.

- [Door + T2 + ~Discrete -> Almost discrete] with (2):
 that's logically the same as [Door + T2 -> Discrete _or_ Almost discrete] with (2).  And with (3) that conclusion would be a single "almost discrete".  That's true.  But having to say "not discrete" in the hypotheses does not seem a big deal to me.  It just says that under some other conditions, if we have at least one non-isolated point, then we have exactly one.

(3) also seems a little inconvenient for users looking for spaces that are almost discrete.  With (3) they would have to filter out discrete spaces explicitly.

We also want to reflect the literature, and (2) seems to have been used by more authors than (3) in that respect.  The only place I could find with (3) are possibly two papers by the same authors, Hirata & Yajima.

@StevenClontz, when you get the opportunity, would you be able to check what almost discrete definition these papers use?

**Comment by danflapjax** [comment]
I guess (2) is fine, even if excluding discrete spaces feels arbitrary to me.

**Comment by danflapjax** [comment]
In the [almost-discrete](https://github.com/pi-base/data/tree/almost-discrete) branch, I decided to take a stab at giving some theorems to the almost discrete property while leaving the choice of (2) vs. (3) ambiguous, so that I and others could compare the two choices. (And so I could write down some of the theorems gradually clogging my head and notes.) All that's needed to disambiguate is to add either Discrete ⇒ Almost discrete or Almost discrete ⇒ ¬Discrete (although a few theorems could be simplified accordingly).

**Comment by StevenClontz** [comment]
> In the [almost-discrete](https://github.com/pi-base/data/tree/almost-discrete) branch, I decided to take a stab at giving some theorems to the almost discrete property while leaving the choice of (2) vs. (3) ambiguous, so that I and others could compare the two choices. (And so I could write down some of the theorems gradually clogging my head and notes.) All that's needed to disambiguate is to add either Discrete ⇒ Almost discrete or Almost discrete ⇒ ¬Discrete (although a few theorems could be simplified accordingly).

It'd be great if you made this a draft PR - it makes it easier to comment on.

**Comment by prabau** [comment]
@danflapjax Another basic result, not deducible from your branch, is Lemma 2.1 in the reference for (1) above:
 [almost discrete ==> normal], and the proof does not need Hausdorff. 
Not sure, but could this be strengthened to completely normal?

**Comment by StevenClontz** [comment]
Every subspace of almost discrete is either almost discrete or discrete, and therefore normal.

**Comment by danflapjax** [comment]
Completed in #922
