### ISSUE TITLE
Problem with T180 and cozero complemented 

### ISSUE THREAD

**Issue by prabau** [pi-base/data#82]
I was wondering why the Odd-even topology (product of discrete countable by two points indiscrete) was showing as not being perfectly normal:
https://topology.jdabbs.com/spaces/S000005/properties/P000015

It is not T6, as it is not even T0, but it should be perfectly normal, as far as I can tell.
The reason seems to be the combination of these two theorems:
T180: Perfectly normal implies cozero complemented
T126: Cozero complemented implies T3.5

The article mentioned in the reference for cozero complemented (https://topology.jdabbs.com/properties/P000061/references), as well as https://www.sciencedirect.com/science/article/pii/S0166864103003766 only mention that notion in the context of Tychonoff spaces.  I assume that's why the definition assumes T3.5.

So it seems we need to change T180 to "T6 implies cozero complemented".
Would you agree?

**Comment by StevenClontz** [comment]
So this is interesting, according to https://topology.pi-base.org/properties/P000061 the pi-Base thinks that "perfectly normal" https://topology.pi-base.org/properties/P000015 implies T_{3.5} https://topology.pi-base.org/properties/P000006 (by way of co-zero complemented). In fact our definition of cozero complemented assumes T_{3.5} (since it's defined in that context).

This reveals a bug here: https://topology.pi-base.org/spaces/S000004/properties/P000015 as any indiscrete space should be perfectly normal vacuously. So I'll make a PR with indiscrete=>perfectlyNormal and fixing T180 as @prabau mentions. I'll toss in indiscrete=>compact as well. @lyengulalp check my work in that upcoming PR.
