### ISSUE TITLE
Property Suggestion: Simply connected

### ISSUE THREAD

**Issue by JoeF131** [pi-base/data#851]
## Property Suggestion

A space is said to be **Simply connected** if it is [path connected](https://topology.pi-base.org/properties/P000037) and any loop $f: S^1 \longrightarrow X$ is retractible. Here $S^1$ is the [circle](https://topology.pi-base.org/spaces/S000170/properties?filter=path).

## Rationale

This property appears in the textbooks "Algebraic Topology" by Allen Hatcher page 28.
See also https://en.wikipedia.org/wiki/Simply_connected_space

## Relationship to other properties

Every [contractable](https://topology.pi-base.org/properties/P000199) space is [simply connected] and every [simply connected] is [path connected](https://topology.pi-base.org/properties/P000037).

**Comment by StevenClontz** [comment]
Simply connected is a good idea to add.

https://topology.pi-base.org/spaces/S000196 would be path connected but not simply connected.

Do we have a simply connected but not contractable space?

**Comment by prabau** [comment]
The sphere $S^2$ is simply connected but not contractible.  Is that in pi-base?

**Comment by prabau** [comment]
See also issue #818, which also covered that suggestion.

**Comment by JoeF131** [comment]
Oh right. I was looking for semi-locally path connected and couldn't find it, so I made this contribution. But if #818 exists, then I should delete this one, as this one is redundant

**Comment by prabau** [comment]
No need to delete.  We can just close it.  But thanks for the suggestion anyway.

**Comment by GeoffreySangston** [comment]
I was planning on adding it in the next few days actually! But don't let that stop you if you feel like working on it. I guess we'll need to be careful not to bump into each other. Otherwise, I'll be adding it. I was currently working on adding contractible to everything. 

I believe the long line is not contractible but is simply connected (1-connected).

**Comment by JoeF131** [comment]
I actually only found this data base recently so I would probably not be a huge help in implementing those.

I wasn't even looking for "simply connected" but rather for CW-complexes and since I haven't seen any suggestion adding those, it might actually be better for me to add those instead of interfering with your current work. Of course I would firstly add another Issue asking whether CW-complexes should even be added to the data base.

The long ray is simply connected. https://en.wikipedia.org/wiki/Long_line_(topology)#Properties

**Comment by yhx-12243** [comment]
> Simply connected is a good idea to add.
> 
> The circle would be path connected but not simply connected.
> 
> Do we have a simply connected but not contractable space?

Currently [S114](https://topology.pi-base.org/spaces/S000114) is.

**Comment by StevenClontz** [comment]
By the above definition, S114 is not simply connected, because it is not path connected.

Is the requirement that `simply connected => path connected` standard?

**Comment by prabau** [comment]
> By the above definition, S114 is not simply connected, because it is not path connected.

You are right, it is not path connected, hence not simply connected.

I had not read the description carefully, and was thinking of the Warsaw circle, which has the desired properties.
https://en.wikipedia.org/wiki/Shape_theory_(mathematics)#Warsaw_circle
I guess that space should be added.

**Comment by GeoffreySangston** [comment]
@StevenClontz I believe so. E.g.

1. [page 28 / pdf page 37 of Hatcher](https://pi.math.cornell.edu/~hatcher/AT/AT.pdf)
2. Spanier (page 51) defines simply connected as 1-connected, which there means continuous maps S^k to X have continuous extension over the corresponding disk, for k = 0 and 1.
3. [nlab](https://ncatlab.org/nlab/show/n-connected+space) uses a similar definition to Spanier.
4. [Wikipedia](https://en.wikipedia.org/wiki/Simply_connected_space) requires the space to be path connected.

When I looked through several textbooks the other day they all seemed to require path connected. It's funny though because I remember somebody emphasizing that we should write "simply connected and connected", though I can't actually find a source which would require this.

**Comment by yhx-12243** [comment]
> > Simply connected is a good idea to add.
> > The circle would be path connected but not simply connected.
> > Do we have a simply connected but not contractable space?
> 
> Currently [S114](https://topology.pi-base.org/spaces/S000114) is.

Sorry for typo, I mean [S115](https://topology.pi-base.org/spaces/S000115), topologist's sine curve with an arc below, this is a good example that "looks like" a circle, they have some property of circle (not contractible) but not homeomorphism to it (it's simply connected).

**Comment by GeoffreySangston** [comment]
Just summarizing everything done here.

1. Simply connected was suggested and added. [P000200](https://topology.pi-base.org/properties/P000200)
2. It was suggested that there be a space which is simply connected and not contractible, and $S^2$ was then suggested. $S^2$ has been added. [000169](https://topology.pi-base.org/spaces/S000169)
3. Warsaw circle was suggested. It has been added. [S000205](https://topology.pi-base.org/spaces/S000205)
4. It was suggested that one of the sine curves satisfies ~contractible + simply connected. This appears to have been mistaken, or applicable to a sine curve not in pi-base.
