### ISSUE TITLE
Trait Suggestion: Add remaining traits for spaces of cardinality <= 3

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#902]
Inspired by @JoeF131's recent PR completing our list of spaces of cardinality 3, I think we should be able to answer all the open-to-pi-Base questions about the traits of all spaces of cardinality at most 3. I'm making a list here to check off...

- [x]  [S11](https://topology.pi-base.org/spaces/S000011) | [P10](https://topology.pi-base.org/properties/P000010)
- [x]  [S164](https://topology.pi-base.org/spaces/S000164) | [P186](https://topology.pi-base.org/properties/P000186)
- [x] [S187](https://topology.pi-base.org/spaces/S000187) | [P89](https://topology.pi-base.org/properties/P000089)
- [x] [S188](https://topology.pi-base.org/spaces/S000188) | a lot lol

**Comment by JoeF131** [comment]
I initially also suggested to get rid of unnecessesary trait for all spaces Cardinality $\leq 3$ https://github.com/pi-base/data/pull/898#issuecomment-2469334620, so one could do that while we're at it. (With the exception of [S7](https://topology.pi-base.org/spaces/S000007), [S203](https://topology.pi-base.org/spaces/S000203) and [S204](https://topology.pi-base.org/spaces/S000204) which we're adjusted in #898 and #901.)

**Comment by yhx-12243** [comment]
[S187](https://topology.pi-base.org/spaces/S000187) is [P89](https://topology.pi-base.org/properties/P000089):

Suppose $f(p) = 2$, then $f^{-1}(2)$ is nonempty open, so including $2$. Otherwise, it follows from [S10 is P89](https://topology.pi-base.org/spaces/S000010/properties/P000089) that $f|_{0,1}$ has a fixed point.

**Comment by StevenClontz** [comment]
> [S187](https://topology.pi-base.org/spaces/S000187) is [P89](https://topology.pi-base.org/properties/P000089):
> 
> Suppose f ( p ) = 2 , then f − 1 ( 2 ) is nonempty open, so including 2 . Otherwise, it follows from [S10 is P89](https://topology.pi-base.org/spaces/S000010/properties/P000089) that f | 0 , 1 has a fixed point.

Implemented as #912

**Comment by david20000813** [comment]
[S11](https://topology.pi-base.org/spaces/S000011) is [P10](https://topology.pi-base.org/properties/P000010):

$\{1\}, \{2\}, X$ form a basis for the topology. $X$ is clearly regular open. $\text{int}(\text{cl}(\{1\})) = \text{int}(\{0, 1\}) = \{1\}$ is regular open, and similarly for $\{2\}$.

**Comment by david20000813** [comment]
[S188](https://topology.pi-base.org/spaces/S000188) is not [P10](https://topology.pi-base.org/properties/P000010):

Since $\{1\}$ is open, any base of the topology must contain $\{1\}$. But $\text{int}(\text{cl}(\{1\})) = \text{int}(\{1, 2\}) = \{1, 2\}$, so $\{1\}$ is not regular open, whence $X$ cannot be semiregular.

**Comment by david20000813** [comment]
[S188](https://topology.pi-base.org/spaces/S000188) is [P49](https://topology.pi-base.org/properties/P000049):

$X$ is the topological sum of the singleton and the Sierpinski space, both of which are extremally disconnected. The topological sums of extremally disconnected spaces are extremally disconnected.

**Comment by david20000813** [comment]
This is now all done, but since a new property Has a closed point (P107) got added, a few spaces now again have unknown traits. As there is still one more theorem to be added for P107, I’ll wait until that gets added to figure out what spaces need P107 traits and if that makes any other currently known traits redundant, and will write a PR accordingly after that.

**Comment by david20000813** [comment]
All finite spaces now have all their traits known.
