### ISSUE TITLE
Add alias "Has a specialized point" for "Has a point with a unique neighborhood"?

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#920]
See discussion at #856.

I feel like the dual property "[Has a point with a unique neighborhood](https://topology.pi-base.org/properties/P202)" of "[Has a generic point](https://topology.pi-base.org/properties/P201)" needs a more obvious alias representing that duality. So while "Has a specialized point" is not in the literature, I wonder if it's appropriate to add it to $\pi$-Base as an alias (not our canonical name)

In #856 there was discussion of "Has a most specialized point". But since we don't say "Has a most generic point", maybe "Has a specialized point" is fine?

**Comment by prabau** [comment]
Let me try to explore the concepts related to the [specialization preorder](https://en.wikipedia.org/wiki/Specialization_(pre)order) on a space $X$.

### Specialization/Generalization relation

Let $x,y\in X$.
If $x\in cl\\{y\\}$ (equivalently, $cl\\{x\\}\subseteq cl\\{y\\}$), one says:
- $x$ is a _specialization_ of $y$
- $y$ is a _generalization_ of $x$

The notation for this is always the "squiggly arrow": $y\rightsquigarrow x$ (it goes from more generalized point to more specialized point).

The relation "is a specialization of" is a preorder.  The relation "is a generalization of" is the reverse preorder.

Now, as explained in the wikipedia page, there are two conventions when defining the "specialization preorder"; it is meant either as the "is a specialization of" preorder, or the "is a generalization of" preorder.

For definiteness, let's pick $x\le y$ to mean $x$ is a specialization of $y$ (i.e., $y\rightsquigarrow x$).
As a particular example, given a preorder $(X,\le)$, one can form the Alexandrov topology on $X$ with the open sets being the upper sets. The more specialized points will be further down and the less specialized points will be further up.

### Maximum, maximal, etc

Given any preorder $(X,\le)$, one says that two elements $x$ and $y$ are _equivalent_ (notation: $x\sim y$) if $x\le y$ and $y\le x$. (For the specialization preorder, that would correspond to $cl\\{x\\}=cl\\{y\\}$, that is, $x$ and $y$ are _topologically indistinguishable_.)

One also defines:
- $x$ is a _maximum_ element if $y\le x$ for all $y\in X$.
- $x$ is a _maximal_ element if any element $y\ge x$ is necessarily equivalent to $x$.
- $x$ is a _minimum_ element if $y\ge x$ for all $y\in X$.
- $x$ is a _minimal_ element if any element $y\le x$ is necessarily equivalent to $x$.

### Applying this to the specialization preorder

Let $(X,\le)$ be the specialization preorder (so $x\le y$ iff $y\rightsquigarrow x$).

(1) Some equivalent formulations for " $x$ is _maximum element_ for $\le$":
- $x$ is a **generic point**
- $x$ is a generalization of every other point
- Every point is a specialization of $x$
- $x$ is more generalized than any other point (where "more generalized" means $\ge$)
- $x$ is less specialized than any other point (where "less specialized" means $\ge$)
- $x$ is a least specialized point (? ambiguous: could be interpreted as (2) below)
- $x$ is a most generalized point (? ambiguous, see (2))

(2) Some equivalent formulations for " $x$ is _maximal element_ for $\le$":
- There is no element strictly more generalized than $x$
- Any generalization of $x$ is topologically indistinguishable from $x$
- $x$ is a most generalized point (? ambiguous, see (1))

(3) Some equivalent formulations for " $x$ is _minimum element_ for $\le$":
- $x$ is a **???**
- $x$ is a specialization of every other point
- Every point is a generalization of $x$
- $x$ is more specialized than any other point (where "more specialized" means $\le$)
- $x$ is less generalized than any other point (where "less generalized" means $\le$)
- $x$ is a least generalized point (? ambiguous: could be interpreted as (4) below)
- $x$ is a most specialized point (? ambiguous, see (4))

(4) Some equivalent formulations for " $x$ is _minimal element_ for $\le$":
- There is no element strictly more specialized than $x$
- Any specialization of $x$ is topologically indistinguishable from $x$
- $x$ is a most specialized point (? ambiguous, see (3))

----
In light of all this, since "$x$ is a most specialized point" already feels ambiguous between (3) and (4), it looks that "$x$ is a specialized point" has an even less clear meaning.  Every point is a specialized point of some point, maybe of itself, maybe of elements topologically indistinguishable from it, maybe of still other points, even if the point does not satisfy (3).

**Comment by GeoffreySangston** [comment]
I think 'other' may as well be removed from all of the characterizations. The possible candidates I see are:
- 'Has a point specializing every point'
- 'Has a point which specializes every point'

I do see the term 'special point' appearing in the contexts of the spectrum of a valuation ring (which I know almost nothing about so forgive me if this is silly). [This post](https://math.stackexchange.com/questions/319467/valuation-rings) says the prime ideals of a valuation ring $R$ are totally ordered by inclusion, so $\mathrm{Spec}(R)$ will have a generic point and a point which specializes every point, which seems to be commonly called the special point. The following pages are examples of this usage
 - https://stacks.math.columbia.edu/tag/01J8
 - https://stacks.math.columbia.edu/tag/054F (this one just for a discrete valuation ring, for which the spectrum has two points)
 - https://stacks.math.columbia.edu/tag/055Q (again for a discrete valuation ring)
 - (Arbitrarily chosen Arxiv paper, among many on Google scholar) https://arxiv.org/pdf/math/9808074
 - The following refers to the 'special point' of the spectrum of a local reduced ring https://pi.math.cornell.edu/~andrescantabria/My_favorite_flatness_results.pdf
 
While researching that, I found an [nlab page defining focal point](https://ncatlab.org/nlab/show/focal+point). A *focal point* of a space is a point for which the only open neighborhood is the entire space (i.e., the concept we're discussing). This page includes the fact that a spectrum of a ring has a focal point if and only if the ring is a local ring. Unfortunately, 'focal point' is another heavily overloaded term on Google scholar, and I didn't see any papers on Google scholar using it in my very very brief search. Nlab does list two sources on the page though, but I don't have access to them. In the talk page for Nlab, Todd Trimble asked if anybody uses this terminology besides Freyd-Scedrov (one of the two sources).

**Comment by prabau** [comment]
I like your suggestion "Has a point specializing every point".

**Comment by prabau** [comment]
Note: #821 is still pending and has changes involving P202.
Any changes here should make sure there are no conflicts.

**Comment by StevenClontz** [comment]
I see no reason to do this until #821 is merged, so no worries there.

I see on https://en.wikipedia.org/wiki/Generic_point that "special point" is a thing ("closed point" would not be great in our context). But I also see at https://en.wikipedia.org/wiki/Zariski_topology#Examples that "special/closed points" are not unique.

So I think "Has a point specializing every point" is the way to go as the new alias.

**Comment by GeoffreySangston** [comment]
What do we thinking about including the nlab 'focal point' page as a reference? It is the same exact concept after all.

**Comment by StevenClontz** [comment]
I think adding a link to the description sounds reasonable. (It's also worth considering whether nLab should be a valid reference in the `refs:` but that discussion is out of scope here.)

I also think "Has a focal point" isn't a bad alias to add either. I cannot find that "Geometric Logic" book cited there, however.

**Comment by GeoffreySangston** [comment]
The following appears in Section C1.5 page 523 of Johnstone's *Sketches of an Elephant: A Topos Theory Compendium* Volume 1 (2002)

> By a *focal point* of a space $X$, we mean a point $x$ whose only neighborhood is the whole of $X$. [...] We say a space is *local* if it has a focal point; this name derives from the fact that the prime spectrum of a local ring is a local space (the focal point being that which corresponds to the unique maximal ideal of the ring).

**Comment by prabau** [comment]
I am not quite sure.  My gut feeling is that pi-base was mainly concerned with topology and should not get too far afield into other areas line commutative algebra, algebraic geometry, etc if there are alternative ways to express a topological concept.  But I'd be very interested to hear your thoughts about this.

It is true that "generic point" comes from algebraic geometry, but it has become used quite a bit in topology itself and is convenient way to express things.

I like "focal point".  But is it a one-off thing that was used in Johnstone a papers about commutative algebra mainly?  Or is it used also in purely topology papers?  It seems it would be worth to check.  Just because one person has used it somewhere may not make it worthwhile to add here if the terminology is not widely used.  But I do like "focal point".

Curious to hear you ideas about this.

**Comment by prabau** [comment]
FYI (related to my comment above):

https://zbmath.org/?q=%22focal+point%22+cc%3A5

zbmath only shows four articles related to topology and mentioning "focal point" as a keyword.  And the meaning is a completely different one, something in dynamical system (an abstraction of to the usual focal point of a parabola it seems).
It seems that in topology if the terminology is used at all, it is usually with a different meaning.

**Comment by prabau** [comment]
https://github.com/pi-base/data/pull/921#issuecomment-2484455568

"Focal point" is a really convenient term to have around.  Maybe it should be an alias, and maybe even more?
