### ISSUE TITLE
Theorem Suggestion: All nonempty hereditarily connected spaces are contractible

### ISSUE THREAD

**Issue by david20000813** [pi-base/data#925]
## Theorem Suggestion

If a space is:

- [Hereditarily connected](https://topology.pi-base.org/properties/P000196)
- not [Empty](https://topology.pi-base.org/properties/P000137)

then it is [Contractible](https://topology.pi-base.org/properties/P000199).

## Rationale

This theorem would demonstrate that no spaces satisfy the following search:

https://topology.pi-base.org/spaces?q=hereditarily+connected+%2B+not+empty+%2B+not+contractible

## Proof/References

Shown in David Gao's [answer](https://math.stackexchange.com/a/5000543/465145) to [Math StackExchange 5000498](https://math.stackexchange.com/questions/5000498/).

**Comment by GeoffreySangston** [comment]
Before adding the theorem you suggest, since there's a possible stronger theorem which might make it redundant, I was wondering if we could figure out if the following is true?  I was hoping to think about it when I have more free time and, but I should probably focus on with my thesis work and can't really afford that right now.

Possible Stronger Theorem: Hyperconnected + Path connected + ~Empty => Contractible. [π-Base, Search for `Hyperconnected + path connected + ~empty + ~contractible`](https://topology.pi-base.org/spaces?q=Hyperconnected+%2B+path+connected+%2B+%7Eempty+%2B+%7Econtractible)

If this is true, it would teach pi-base about the contractibility of two spaces not covered by 'Hereditarily connected => contractible', namely S16 and S19: [π-Base, Search for `path connected + hyperconnected + ~hereditarily connected + ~Has a point with a unique neighborhood + ~Has a generic point`](https://topology.pi-base.org/spaces?q=path+connected+%2B+hyperconnected+%2B+%7Ehereditarily+connected+%2B+%7EHas+a+point+with+a+unique+neighborhood+%2B+%7EHas+a+generic+point)

(Note that Hereditarily connected => Hyperconnected: [π-Base, Search for `Hereditarily connected + ~hyperconnected`](https://topology.pi-base.org/spaces?q=Hereditarily+connected+%2B+%7Ehyperconnected) )

There's a neat proof of 'Has a cofinite topology + path connected (+ ~Empty) => contractible' on the following blog, which is a weaker statement than Possible Stronger Theorem. Maybe it's possible to adapt the proof there? (Though I guess it could turn out that S19 is not contractible, which would be the ideal counterexample for pi-base.) 
 - https://lovelylittlelemmas.rjprojects.net/a-strange-contractible-space/

**Comment by david20000813** [comment]
> Before adding the theorem you suggest, since there's a possible stronger theorem which might make it redundant, I was wondering if we could figure out if the following is true? I was hoping to think about it when I have more free time and, but I should probably focus on my thesis work and can't really afford that right now.
> 
> Possible Stronger Theorem: Hyperconnected + Path connected + ~Empty => Contractible. [π-Base, Search for `Hyperconnected + path connected + ~empty + ~contractible`](https://topology.pi-base.org/spaces?q=Hyperconnected+%2B+path+connected+%2B+%7Eempty+%2B+%7Econtractible)
> 
> If this is true, it would teach pi-base about the contractibility of two spaces not covered by 'Hereditarily connected + ~Empty => contractible', namely S16 and S19: [π-Base, Search for `path connected + hyperconnected + ~hereditarily connected + ~Has a point with a unique neighborhood + ~Has a generic point`](https://topology.pi-base.org/spaces?q=path+connected+%2B+hyperconnected+%2B+%7Ehereditarily+connected+%2B+%7EHas+a+point+with+a+unique+neighborhood+%2B+%7EHas+a+generic+point)
> 
> (Note that Hereditarily connected => Hyperconnected: [π-Base, Search for `Hereditarily connected + ~hyperconnected`](https://topology.pi-base.org/spaces?q=Hereditarily+connected+%2B+%7Ehyperconnected), and Hereditarily connected => contractible => path connected. )
> 
> There's a neat proof of 'Has a cofinite topology + path connected (+ ~Empty) => contractible' on the following blog, which is a weaker statement than Possible Stronger Theorem. Maybe it's possible to adapt the proof there? (Though I guess it could turn out that S19 is not contractible, which would be the ideal counterexample for pi-base.)
> 
> * https://lovelylittlelemmas.rjprojects.net/a-strange-contractible-space/

I spent some time thinking about S19. I doubt it is even simply connected, but I wasn’t able to find a proof. Regardless, the possible stronger theorem you suggested is false. In the other answer to the MSE question I linked to, I constructed a nonempty ultraconnected space which is not contractible. Ultraconnected spaces are path connected (T38). In fact, that space is even simply connected - I’m planning to add this to the answer later, but the argument is that, per Lemma 2 in that answer, the range of any path has a minimum point under $\leq$. But then that point will be a specialized point of the range (I think specialized point is what people are leaning towards calling the dual of generic point? I just mean a point which is contained in all nonempty closed sets.), so the range of any path is contractible (T601), from which simple connectedness easily follows. The space in question is also hyperconnected - again, I’m adding this to the answer later. The argument is that, in order to verify hyperconnectedness, it suffices to show any two nonempty basic open sets intersect. The topology is defined using a closed subbasis, so dualizing between open and closed sets, one can see that it suffices to show any finite union of elements of the closed subbasis is not the entire space. This is true because any finite union of $T_x$ and $K_n$ has a uniform upper bound on lengths of elements. Hence, the following substantial weakening of your suggested theorem is even false:

Hyperconnected + Ultraconnected + Simply connected + ~Empty => Contractible

On a side note, there is a way to simultaneously generalize the following four theorems:

1. Hereditarily connected + ~Empty => Contractible (the theorem I’m suggesting);
2. Has a generic point => Contractible (T591);
3. Has a point with a unique neighborhood => Contractible (T601);
4. Indiscrete + ~Empty => Contractible (T584).

The result is that, if the space has a point which is comparable to every point under the specialization preorder, then it is contractible. The proof is exactly the same as my proof of Hereditarily connected + ~Empty => Contractible, just with $x_0$ chosen specifically to be that special point. The map constructed, with some slight modifications on what to do with points equivalent to $x_0$ under the specialization preorder, will also just reduce to the maps constructed in the proofs of T591, T601, and T584, in case the space satisfies the requirements of those theorems. This is probably the most general that can be done in this direction of “highly connected” non-$T_1$ spaces being contractible. (Unfortunately it won’t imply Has a cofinite topology + Path connected + ~Empty => Contractible, but that’s in the $T_1$ case, a different direction that these non-$T_1$ theorems.) However, I don’t know if this condition - Have a point comparable to every point under the specialization preorder - has been given a name or otherwise studied in the literature before.

**Comment by prabau** [comment]
@david20000813 FYI, we were well aware of the suggested theorem, as this is part of work in progress in pi-base.
See the discussion at the end of #921.
We asked about it in mathse to have a source to reference it.

**Comment by prabau** [comment]
@david20000813 FYI, we were well aware of the suggested theorem, as this is part of work in progress in pi-base.
See the discussion at the end of #921.
We asked about it in mathse to have a source to reference it.

> But then that point will be a specialized point of the range (I think specialized point is what people are leaning towards calling the dual of generic point? I just mean a point which is contained in all nonempty closed sets.),

We were leaning towards the terminology "focal point" (used in Johnstone for example).  See #924 (still pending review from someone) and the discussion in #920.

**Comment by GeoffreySangston** [comment]
@david20000813 Wow what a generous post! Thanks for sharing. I'd really like to study your MSE counterexample soon.

**Comment by prabau** [comment]
Interesting observation about generalizing four theorems into one.  Unfortunately, the general guideline for pi-base is to avoid adding new properties if they have not been studied in the literature.  Like @StevenClontz is used to say, pi-base's business is to reflect peer-reviewed mathematics, more than peer-reviewing mathematics.

We have made occasional exceptions for a property that may not have a name, but is extremely convenient to avoid duplication.  Whether this qualifies or not would have to be debated.

So for now, to get things moving I will
- add the proposed theorem
- remove T584, which can be deduced from the other ones.

Then maybe @GeoffreySangston can review and get this merged later today.

**Comment by david20000813** [comment]
@prabau That’s good to know. And as I already mentioned to Geoffrey, neither ultraconnected, nor hyperconnected + path connected (nor even combining the two, plus simply connected), will imply contractibility, so it seems going from hereditarily connected is the current best possible result, unless someone can find a reference and a name for the property that there is a point comparable to every point in the specialization preorder. I’m aware that pi-base doesn’t usually add properties not already present in the literature, which is why I’m not suggesting to add this new property now, instead I’m just saying if it happens that this has appeared in the literature, then adding this property and that it implies contractibility might be better, that’s all.

**Comment by GeoffreySangston** [comment]
@david20000813 Since this comment thread is likely to be buried eventually, and since you say the proof is the exact same as the text which already appears in the answer, what do you think about editing the text of your first answer to indicate the following?

>, if the space has a point which is comparable to every point under the specialization preorder, then it is contractible.

Then if we every do find the concept in the literature then we can just link to your post if pi-base adds it (but I also just think it's a nice remark).

**Comment by david20000813** [comment]
@GeoffreySangston Thanks for the suggestion. I’ll do that, yes. Let me first edit my answer on ultraconnected spaces to include some additional properties I’d like to include regarding $X$. Then I’ll get to that.

**Comment by prabau** [comment]
Added a PR for the proposed theorem.  It's ready to review.

**Comment by prabau** [comment]
> In the other answer to the MSE question I linked to, I constructed a nonempty ultraconnected space which is not contractible.

@david20000813 I will add your example to pi-base and let you give review comments if needed.

**Comment by david20000813** [comment]
@prabau Great! Thank you!

**Comment by david20000813** [comment]
@prabau By the way, I forgot to ask, but what is the planned name for this example? I personally prefer a name that has "binary tree" in it, since that is the intuition behind the construction.

**Comment by prabau** [comment]
> @prabau By the way, I forgot to ask, but what is the planned name for this example? I personally prefer a name that has "binary tree" in it, since that is the intuition behind the construction.

It will be a surprise. :-)  Working on it right now and will have a PR ready later today. Then people can comment and give suggestions.

**Comment by david20000813** [comment]
@prabau In that case I'll leave it to you and wait to comment when the PR is ready.

**Comment by GeoffreySangston** [comment]
@david20000813 @prabau 

I'm not suggesting we add this property, and really I'm just sharing this because it's kind of fun. While looking around for the source of *non-Hausdorff cone*, I saw that on page 30 of [Barmak](https://books.google.com/books?hl=en&lr=&id=KR3zCAAAQBAJ&oi=fnd&pg=PR3&dq=barmak+algebraic+topology+finite&ots=ACLB1lOyjw&sig=Zy4Wp7iHxSyu9ll4eb-zOop3eUo#v=onepage&q=barmak%20algebraic%20topology%20finite&f=false), he defines the *star* of a point $p$ in a finite $T_0$ space $X$ to be the set of points which are comparable with $x$ (under the specialization preorder). He also mentions that stars are contractible. So 'Is the specialization preorder star of some point' is more or less an appearance in published literature of the property requested in https://github.com/pi-base/data/issues/925#issuecomment-2489753794. It would be great if someone called this 'Starshaped with respect to the specialization preorder '.

(That chapter has some other interesting things.)

**Comment by prabau** [comment]
Hmm, not saying it's a bad thing and I have not even looked at Barmak's paper. But there are so many papers out there, and anybody can come up with new concepts to study and new terminology.  Something that has only appeared in one of two papers and does not seem to have captured the interest of many more topologists may not necessarily need to be in pi-base.  Just my $0.02.

**Comment by david20000813** [comment]
@GeoffreySangston This does look quite interesting and seems like the closest we can get to the property I want of having a point comparable to every point. Though, I suppose at this point I'm somewhat neutral on whether to add this. While I think it will be great to have a single theorem combining the three known theorems on non-$T_1$ spaces being contractible, I have to admit the property doesn't seem to do much apart from implying contractibility.

**Comment by prabau** [comment]
P102: If the second bullet references zb:0116.14303, that references should be in the `refs:`.  But I checked and that ref does not seem to have a Theorem 3.2 ?

**Comment by GeoffreySangston** [comment]
> @GeoffreySangston I spent some time thinking about S19. I doubt it is even simply connected, but I wasn’t able to find a proof. 

@david20000813 I asked this question on [MSE](https://math.stackexchange.com/questions/5009984/is-the-real-number-line-mathbbr-with-the-compact-complement-topology-simply).

**Comment by david20000813** [comment]
> > @GeoffreySangston I spent some time thinking about S19. I doubt it is even simply connected, but I wasn’t able to find a proof.
> 
> @david20000813 I asked this question on [MSE](https://math.stackexchange.com/questions/5009984/is-the-real-number-line-mathbbr-with-the-compact-complement-topology-simply).

@GeoffreySangston Just saw that. I hope we can get a conclusive answer soon.

On the other hand, I noted one of the MSE posts linked in your post, [Is the compact complement topology locally arc connected?](https://math.stackexchange.com/questions/2272139/is-the-compact-complement-topology-locally-arc-connected). It seems the current proof for [S19 being locally arc connected on pi-Base](https://topology.pi-base.org/spaces/S000019/properties/P000043), is still wrong. I'll write a PR addressing this.

**Comment by GeoffreySangston** [comment]
@david20000813 @prabau Yes, I also noticed this. I felt bad that I've opened a lot of issues lately so I was postponing raising another haha.

**Comment by GeoffreySangston** [comment]
Just summarizing what happened here. The short conclusion is that everything either has been addressed, or is being addressed and won't be lost by closing this.

1. OP suggested adding Hereditarily connected + ~Empty => Contractible. It is added in [T585](https://topology.pi-base.org/theorems/T000585).
2. I speculated about a possible improvement in https://github.com/pi-base/data/issues/925#issuecomment-2489051254. Right now I'm not sure if such speculation is good or bad pi-base practice, but in this case it seems to have been good because see item 3. 
3. @david20000813 found a strong counterexample to the suggestion. (@david20000813 may have already been thinking in that direction without my speculation.) The counterexample has been added [S000100](https://topology.pi-base.org/spaces/S000100)
4. @david20000813's comment https://github.com/pi-base/data/issues/925#issuecomment-2489535443 which shared reference to the counterexample also explained how to generalize four theorems given the addition of a new property. I found a semi-valid reference to the property in a textbook, but we are all in agreement that it's not worth adding this property at present.
5. Tangential to this issue, I speculated about contractibility of S19 in https://github.com/pi-base/data/issues/925#issuecomment-2489051254, and @david20000813 suggested it's not even simply connected. I asked a question on [MSE](https://math.stackexchange.com/questions/5009984/is-the-real-number-line-mathbbr-with-the-compact-complement-topology-simply) about it. 
6. @david20000813 raised a separate PR to fix the issue of S19's locally arc connected trait-file.
